#! /bin/bash 



# so this is a hello world program

echo "hello world" 

echo our *communism flash baks* bash version iz  $BASH_VERSION 
echo $BASH 
echo $HOME 
echo $DOWNLOADS 
echo $PWD 

val=10

name=ussrlovah 
echo  the guys name that loves powershell programming is  $name
echo yoo i got $val out of 10! 

#echo "enter age plszzzi wanna sell data!1!1!1" 
#read age 
#echo "your age is $age years old" 
echo "also i got data!!!!! " 
echo "python bootsliper johnsena arch linux xmonad gnome all desktop enviorments" 
echo "would you like to install packages?  " 
echo "enter your names" 
read name1 name2 name3 name4 
echo "your names are.... : $name1 $name2 $name3 $name4"  
read -p 'religion: ' religion_var 
echo "religion? :" $religion_var 
read -sp 'enter your password' password_var 
echo "your password is : " $password_var
echo "enter names again" 
read -a names 
echo "Names" ${names[0]},${names[1]} 
echo "enter where kayne east is" 
read 
echo "ok his location is" $REPLY 
echo $0 $1 $2 $3 "> names"
args=("$@") 
echo ${args[0]},${args[1]}.${args[2]},${args[3]} 



echo "would you like to install the following packages " $packages
word="Y" 
read word

if [[ $word == "Y" ]] 
then 
	echo "installing packages....."  
elif [[  $word = "A" ]]  
then 
	echo "CANCELLED INSTALLATION SELF DESTRUCT = ON"
else 
	echo "cancelled"
fi

echo -e "enter name of da file \c "  
read file_name 

if [[ -e $file_name ]]  
then 
echo "it exists"
if [ -w $file_name ] 
then 
echo "permession accepted" 
cat >> $file_name
else  
	echo "permission denied bozo"
fi
else 
	echo "$file_name not found so L bozo baddddd rario"
fi 
echo "what is your age?"
age=25 
read age

if [ "$age" -gt 18 ] && [ "$age" -lt 69 ] #you can add "-a instead of making seprate brackets and adding && butt you need to add brackets like this [#here you gonna put the stuff like the age and yes add the -a in the middle after the first one[]]"
then 
	echo "i am bigger better stronger"
else 
	echo "i am not biger or better or stronger" 
fi 
echo "what is your pets age" 
petage=7
read petage 
if [ "$petage" -gt 4   ] || ["$petage" -lt 20  ]  # you can add -o instead of making seperate brackets and adding the the or simbole but you need to add brackets like this "[[you will type here the petage and like that]"]
then 
	echo "damn hes big" 
else "bro pets cannot live more than 20 years :skull:" 
fi 

echo "solve this problem what's 150 + 10"
num1=150 
num2=10  
read 
if [ $(( num1 + num2 )) -eq $REPLY  ] 
then

	echo "you got it right its really " 
else 
	echo "bro its so easy how are you so dumb :skull:"  


fi 



echo "the answer was" $(( num1 + num2 )) 

echo "now solve this whats 5 x 5" 
num3=5 
num4=5
read 
if [ $(( num3 * num4 )) -eq $REPLY ] 
then 
	echo "you got it right the answer is bellow" 

else 
	echo "bruh so dumb this so ez" 

fi 

echo "the answer was" $(( num3 * num4 )) 

echo "nice your good how about this  " 
num5=15
num6=5 
read 
 
if [[ $(( num5 / num6 )) -eq $REPLY ]] 
then
	echo "your good there is a final one and you will be free "  

 
	
	
		 
	
	else 
		echo "you suck at math"


fi 



echo "answer is  " $(( num5 / num6  )) 


echo "ok this is the final one lets go" 
num7=170 
num8=30 
read 
if [ $(( num7 - num8 )) -eq $REPLY ] 
then 
	echo "nice no more questions the answer will be down"  

else 
	echo "you suck so bad L" 
fi 

echo "the answer was" $(( num7 - num8  ))

echo "bye" 


#decimal numbers arthemitic operators  
num9=20.5
num10=5
echo "heres part two but we will be practicing with decimals" 
echo "whats 20.5 + 5" 
read 
if [ $(( num9 + num10 )) | bc -eq $REPLY ] 
then 
echo "yo nice "

else 
echo "you suck " 

fi 

echo "answer was "  $(( num9 + num10 )) | bc  







